### ISSUE TITLE
编译不了，MainActivity的R.id.rl_like找不到

### ISSUE THREAD

**Issue by hefuyicoder** [wangshouxue/LikeDemo#1]

**Comment by wangshouxue** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/16813435/162137757-baf3b69e-dff0-47ad-8281-6c6bb7e4af24.png">
我这边试了下下载下来编译正常运行，关于您说的R.id.rl_like在activity_main.xml布局文件中是存在的

**Comment by hefuyicoder** [comment]
可以了，感谢哈
